### PR TITLE
Added the changes to call the REST API from and add a cycle  value to it 

### PR DESCRIPTION
**Pull request by antonyaneeta**
The Structur eresponse form the a Group resposne is a bit complex and we may need furthe rchanges to  display it properly to UI or  when saving the offers we need to add few fields to the all providers and masterAType in our DB

### CODE REVIEW

**Comment by antonyaneeta** [comment]
GET Master Agreement Offers
https://agiledev3a.pythonanywhere.com/p3aplatform/api/agreement_offers
 
POST Response:
https://agiledev3a.pythonanywhere.com/p3aplatform/api/post_ma_offer_response?offerId=6&isAccepted=True
Need 2 parameters : offerId and isAccepted (CASE SENSITIVE) (offerId you can get from our get api)

**Comment by antonyaneeta** [comment]
@pparaska 

Please veriy this and if ok , merge to main and test in your local please .

**Comment by antonyaneeta** [comment]
@Sonam-22  http://localhost:8080/api/fetchoffersforui API 
created will be used on page load of OFFER by Sonam in our UI component


@pparaska  after thais 
On display and accepting th eoffer in provider level for MAType , we need to call the save or PUT API to update the backend our DB aslo  
on Save we should POST to the the group 3 with  a POST API to them regarfingaddign the the accepted flag and oferId 

POST Response:
https://agiledev3a.pythonanywhere.com/p3aplatform/api/post_ma_offer_response?offerId=6&isAccepted=True
Need 2 parameters : offerId and isAccepted (CASE SENSITIVE) (offerId you can get from our get api)

**Comment by antonyaneeta** [comment]
@poonam A logic to update cycle in each role domain provide rlevel is added now. , please check that too

Also, after initia fetch get all offers form our DB with URL   with , http://localhost:8080/api/getAlloffers

@Sonam-22 
We can see if the offer structure is too complex for ui render and other purposes.
After adding clyle for now in our DB offes is saved like below

```
[
    {
        "id": 1,
        "roleName": "Data Architect",
        "experienceLevel": "INTERMEDIATE",
        "technologiesCatalog": "Uncommon",
        "domainId": 2,
        "domainName": "Data",
        "masterAgreementTypeId": 1,
        "masterAgreementTypeName": "MAT1",
        "provider": [
            {
                "id": 1,
                "accepted": false,
                "offerId": "6",
                "name": "provider_y",
                "quotePrice": 2000,
                "isAccepted": false,
                "cycle": 1
            }
        ]
    },
    {
        "id": 2,
        "roleName": "DevOps Eng",
        "experienceLevel": "JUNIOR",
        "technologiesCatalog": "Common",
        "domainId": 4,
        "domainName": "Operations",
        "masterAgreementTypeId": 2,
        "masterAgreementTypeName": "MAT2",
        "provider": [
            {
                "id": 2,
                "accepted": true,
                "offerId": "3",
                "name": "FRAUAS",
                "quotePrice": 2000,
                "isAccepted": true,
                "cycle": 1
            }
        ]
    },
    {
        "id": 3,
        "roleName": "Infrastructure Engineer",
        "experienceLevel": "ADVANCED",
        "technologiesCatalog": "Rare",
        "domainId": 4,
        "domainName": "Operations",
        "masterAgreementTypeId": 2,
        "masterAgreementTypeName": "MAT2",
        "provider": [
            {
                "id": 3,
                "offerId": "5",
                "name": "provider_y",
                "quotePrice": 4600,
                "cycle": 1
            }
        ]
    },
    {
        "id": 4,
        "roleName": "Service operator",
        "experienceLevel": "INTERMEDIATE",
        "technologiesCatalog": "Common",
        "domainId": 4,
        "domainName": "Operations",
        "masterAgreementTypeId": 1,
        "masterAgreementTypeName": "MAT1",
        "provider": [
            {
                "id": 4,
                "offerId": "1",
                "name": "FRAUAS",
                "quotePrice": 2500,
                "cycle": 2
            },
            {
                "id": 5,
                "offerId": "4",
                "name": "provider_y",
                "quotePrice": 2000,
                "cycle": 1
            }
        ]
    },
    {
        "id": 5,
        "roleName": "Solution Architect",
        "experienceLevel": "ADVANCED",
        "technologiesCatalog": "Rare",
        "domainId": 1,
        "domainName": "DevAndConsult",
        "masterAgreementTypeId": 1,
        "masterAgreementTypeName": "MAT1",
        "provider": [
            {
                "id": 6,
                "offerId": "2",
                "name": "FRAUAS",
                "quotePrice": 5000,
                "cycle": 1
            }
        ]
    }
]
```

**Comment by pparaska** [comment]
PR Looks good. Did check on a logic to update cycle in each role domain provider level.

**Pull request merged**
